// Auto-generated by scripts/build-content.js from /content/projects — do not edit by hand.
// To change a project, edit its folder in /content/projects/ instead.
const projects = [
  {
    "slug": "sound-structures",
    "title": "Sound Structures",
    "year": "2022",
    "category": "Research",
    "image": "images/projects/sound-structures.jpg",
    "ratio": 1.7778
  },
  {
    "slug": "mini-lab-kinetic-sculpture",
    "title": "MINI LAB Kinetic Sculpture",
    "year": "2023",
    "category": "Brand Experience",
    "image": "images/projects/mini-lab-kinetic-sculpture.jpg",
    "ratio": 1.4988
  },
  {
    "slug": "hyundai-bubble-nexo",
    "title": "Hyundai Bubble Nexo",
    "year": "2021",
    "category": "Brand Experience",
    "image": "images/projects/hyundai-bubble-nexo.jpg",
    "ratio": 1.7885
  },
  {
    "slug": "soft-spaces",
    "title": "Soft Spaces",
    "year": "2025",
    "category": "Exhibition",
    "image": "images/projects/soft-spaces.jpg",
    "ratio": 0.7737
  },
  {
    "slug": "inflatable-formworks",
    "title": "Inflatable Formworks",
    "year": "2021",
    "category": "Research",
    "image": "images/projects/inflatable-formworks.jpg",
    "ratio": 1.4988
  },
  {
    "slug": "pop-up-prints",
    "title": "Pop Up Prints",
    "year": "2021",
    "category": "Research",
    "image": "images/projects/pop-up-prints.JPG",
    "ratio": 1.4988
  },
  {
    "slug": "the-procrastinator",
    "title": "The Procrastinator",
    "year": "2020",
    "category": "Installation",
    "image": "images/projects/the-procrastinator.jpg",
    "ratio": 0.6672
  },
  {
    "slug": "aircraft-passenger-service-unit",
    "title": "Aircraft Passenger Service Unit",
    "year": "2024",
    "category": "R&D",
    "image": "images/projects/aircraft-passenger-service-unit.jpeg",
    "ratio": 1.7902
  },
  {
    "slug": "ultrabar-assistance-system",
    "title": "Ultrabar Assistance System",
    "year": "2017",
    "category": "R&D",
    "image": "images/projects/ultrabar-assistance-system.jpeg",
    "ratio": 1.5
  },
  {
    "slug": "interactive-train-exhibit",
    "title": "Interactive Train Exhibit",
    "year": "2022",
    "category": "Brand Experience",
    "image": "images/projects/interactive-train-exhibit.jpg",
    "ratio": 1.7778
  },
  {
    "slug": "hornbach-das-herrenzimmer",
    "title": "Hornbach das Herrenzimmer",
    "year": "2015",
    "category": "Set Design",
    "image": "images/projects/hornbach-das-herrenzimmer.jpg",
    "ratio": 1.5184
  },
  {
    "slug": "playmobil",
    "title": "Playmobil Interactive",
    "year": "2026",
    "category": "Retail",
    "image": "images/projects/playmobil.jpg",
    "ratio": 1.5006
  },
  {
    "slug": "liquid-glass-interface",
    "title": "Liquid Glass Interface",
    "year": "2026",
    "category": "R&D",
    "image": "images/projects/liquid-glass-interface.png",
    "ratio": 0.7558
  }
];
